name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        users: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            jkvuacamila/hello-fastapi:latest
            jkvuacamila/hello-fastapi:${{ github.sha }}

      - name: setup Kustomize
        uses: imranismail/setup-kustomize@v2
        
      - name: Update kustomization.yaml
        run: |
          cd k8s
          kustomize edit set image hello-fastapi=jkvuacamila/hello-fastapi-k8s:$GITHUB_SHA

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit -am "Update kustomization.yaml with new image"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: {{ github.ref }}